// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyiqybaenhtoxrjaqzes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5aXF5YmFlbmh0b3hyamFxemVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Mzg2OTIsImV4cCI6MjA2OTAxNDY5Mn0.AdBjEltDtehYmeyjnVhW2MbugxecoqaQECDjXwsuiZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});